job_title = [('Core staff                                        ', 'Core staff'),
    ('Drivers                                           ', 'Drivers'),
    ('Cleaning staff                                    ', 'Cleaning staff'),
    ('High skill tech staff                             ', 'High skill tech staff'),
    ('Sales staff                                       ', 'Sales staff'),
    ('Laborers                                          ', 'Laborers'),
    ('Accountants                                       ', 'Accountants'),
    ('Managers                                          ', 'Managers'),
    ('Security staff                                    ', 'Security staff'),
    ('Cooking staff                                     ', 'Cooking staff'),
    ('Medicine staff                                    ', 'Medicine staff'),
    ('IT staff                                          ', 'IT staff'),
    ('Realty agents                                     ', 'Realty agents'),
    ('Secretaries                                       ', 'Secretaries'),
    ('Waiters/barmen staff                              ', 'Waiters/barmen staff'),
    ('Private service staff                             ', 'Private service staff'),
    ('HR staff                                          ', 'HR staff'),
    ('Low-skill Laborers                                ', 'Low-skill Laborers'), ]
housing_type = [('House / apartment                                 ', 'House / Apartment'),
    ('With parents                                      ', 'With parents'),
    ('Municipal apartment                               ', 'Municipal apartment'),
    ('Co-op apartment                                   ', 'Co-op apartment'),
    ('Rented apartment                                  ', 'Rented apartment'),
    ('Office apartment                                  ', 'Office apartment'), ]
family_status = [('Married                                           ', 'Married'),
    ('Separated                                         ', 'Separated'),
    ('Civil marriage                                    ', 'Civil Marriage'),
    ('Single / not married                              ', 'Single / Not Married'),
    ('Widow                                             ', 'Widow'), ]
education_type = [('Secondary / secondary special                     ', 'Secondary / Secondary Special'),
    ('Higher education                                  ', 'Higher Education'),
    ('Incomplete higher                                 ', 'Incomplete Higher'),
    ('Lower secondary                                   ', 'Lower Secondary'), ]
income_type = [('Commercial associate                              ', 'Commercial Associate'),
    ('Working                                           ', 'Working'),
    ('State servant                                     ', 'State several'),
    ('Student                                           ', 'Student'),
    ('Pensioner                                         ', 'Pensioner')]
