name: Build and Deploy Django App

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          DOCKER_USER=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=$DOCKER_USER/easy-credit-eligibility-checker
          TAG=$(echo ${{ github.sha }} | head -c 7)
          
          # Build the image
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .app/
          
          # Push the image with both tags
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKER_USER }}/easy-credit-eligibility-checker
            docker pull $IMAGE_NAME:latest
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml up -d
